title: Crypto Makr
author: strangedaze
email: contact@cryptomakr.com
description: > # We want to help our users find freedom within their financial lives. 

# social links
twitter_username: Makrcrypto
github_username:  strangedaze

show_excerpts: true # set to false to remove excerpts on the homepage
